USE PATHOX

GO

CREATE TABLE FIRMA_DIGITALE_BIRDID
(
	ID PRIMARY KEY NOT NULL IDENTITY,
	DOCUMENTO VARCHAR(14),
	CLIENTE_ID VARCHAR(100),
	CLIENTE_SEGRETO VARCHAR(100),
	NUMERO_ACESSO VARCHAR(100),
	DATA_DI_SCADENZA DATETIME,
	ELIMINATO BIT
)